exclude: ['README.md', 'Gruntfile.js', 'src/', 'node_modules', 'package.json']
permalink: /:year/:month/:title
paginate: 12
markdown: kramdown
sass:
    sass_dir: css
    style: :compressed
gems:
    - jekyll-feed
